# Generated by Django 3.2.5 on 2021-09-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='monday_opening',
            field=models.TimeField(blank=True),
        ),
    ]
