# Generated by Django 3.2.5 on 2021-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='restaurants',
            field=models.ManyToManyField(default='None', to='api.Restaurant'),
        ),
    ]
