# Generated by Django 3.2.5 on 2021-09-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrightswipes',
            name='room',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
