# Generated by Django 3.2.5 on 2021-09-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210908_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
    ]
