# Generated by Django 3.2.5 on 2021-08-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
