# Generated by Django 3.2.5 on 2021-09-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurant_monday_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='monday_closing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
