# Generated by Django 3.2.5 on 2021-09-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210911_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_username',
            field=models.CharField(max_length=50),
        ),
    ]
