# Generated by Django 3.2.5 on 2021-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_host_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='host_username',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
